version: '3'
services:
  hbase-master:
    image: junit/hbase-master
    environment:
      - HBASE_CONF_hbase_rootdir=hdfs://hdfs-namenode:8020/hbase
      - HBASE_CONF_hbase_master_port=60000
      - HBASE_CONF_hbase_master_info_port=60010
      - HBASE_CONF_hbase_zookeeper_quorum=zookeeper
    ports:
      - 60010:60010
    depends_on:
      - zookeeper
      - hdfs-namenode
  hbase-region:
    image: junit/hbase-region
    environment:
      - HBASE_CONF_hbase_rootdir=hdfs://hdfs-namenode:8020/hbase
      - HBASE_CONF_hbase_master=hbase-master:60000
      - HBASE_CONF_hbase_regionserver_info_port=60030
      - HBASE_CONF_hbase_zookeeper_quorum=zookeeper
    ports:
      - 60030:60030
    depends_on:
      - hbase-master

  zookeeper:
    image: zookeeper:3.4

  hdfs-namenode:
    image: junit/hdfs-namenode:3.2.4
    environment:
    - CLUSTER_NAME=hdfs-cluster
    - CORE_CONF_hadoop_proxyuser_root_hosts=*
    - CORE_CONF_hadoop_proxyuser_root_groups=*
    - HDFS_CONF_dfs_permissions_superusergroup=root
    - HDFS_CONF_dfs_replication=1
    ports:
    - 8020:8020
    - 50070:50070
    - 9870:9870
    volumes:
    - name:/hadoop/dfs/name
  hdfs-datanode:
    image: junit/hdfs-datanode:3.2.4
    environment:
    - CORE_CONF_fs_defaultFS=hdfs://hdfs-namenode:8020
    - CORE_CONF_hadoop_proxyuser_root_hosts=*
    - CORE_CONF_hadoop_proxyuser_root_groups=*
    - HDFS_CONF_dfs_permissions_superusergroup=root
    - HDFS_CONF_dfs_replication=1
    - HDFS_CONF_dfs_datanode_data_dir=file:///hadoop/dfs/data
    volumes:
    - data-0:/hadoop/dfs/data
    depends_on:
    - hdfs-namenode

volumes:
  data-0:
  name:
